type: app
description: Default stackfile usecase description
# template used to create the project
template: igor_stack_advanced_tests/<template-name>
inputs:
  some_input: value
# list of plugins to be applied after project creation
plugins:
  - plugin: igor_stack_advanced_tests/<plugin-name>
    inputs:
      some_input: value
      some_list:
        - item1
        - item2
