name: plugin_sample_3
description: Plugin sample 3
display-name: plugin_sample_3
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/plugin/#category
compatibility:
  - java
  - spring
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/yaml/#technologies
  - "Api"
types:
  - app
inputs:
  - label: Plugin 3 input sample
    type: text
    name: example
    default: plugin3
requirements:
  - igor_stack_advanced_tests/plugin_sample_1
  - igor_stack_advanced_tests/plugin_sample_2
